bind 0.0.0.0
protected-mode yes
port 6379
requirepass SenderPlatform2026SecureRedis!
masterauth SenderPlatform2026SecureRedis!
rename-command REPLICAOF ""
rename-command SLAVEOF ""
rename-command MODULE ""
rename-command DEBUG ""
rename-command CONFIG ""
save 60 1
loglevel warning
