"""create initial tables

Revision ID: 33d0f584c551
Revises: 
Create Date: 2026-06-15 09:51:21.314322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33d0f584c551'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.Enum('WHATSAPP', 'TELEGRAM', 'RUBIKA', 'BALE', name='platformtype'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RESTING', 'BANNED', 'REQUIRES_LOGIN', name='accountstatus'), nullable=False),
    sa.Column('proxy_url', sa.String(length=512), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_platform_status', 'accounts', ['platform', 'status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('subject_type', sa.String(length=128), nullable=True),
    sa.Column('subject_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.Enum('WHATSAPP', 'TELEGRAM', 'RUBIKA', 'BALE', name='platformtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='campaignstatus'), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=True),
    sa.Column('use_gpt', sa.Boolean(), nullable=False),
    sa.Column('include_products', sa.Boolean(), nullable=False),
    sa.Column('schedule_start_at', sa.DateTime(), nullable=True),
    sa.Column('live_rate_revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone_e164', sa.String(length=32), nullable=True),
    sa.Column('telegram_hint', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('consent_status', sa.Enum('UNKNOWN', 'OPTED_IN', 'OPTED_OUT', name='consentstatus'), nullable=False),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.Column('extra_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_phone_e164'), 'contacts', ['phone_e164'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=1024), nullable=True),
    sa.Column('chunk_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding_ref', sa.String(length=512), nullable=True),
    sa.Column('visibility', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_documents_chunk_id'), 'kb_documents', ['chunk_id'], unique=False)
    op.create_table('product_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_snapshots_payload_hash'), 'product_snapshots', ['payload_hash'], unique=False)
    op.create_table('rate_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.Enum('WHATSAPP', 'TELEGRAM', 'RUBIKA', 'BALE', name='platformtype'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('per_second', sa.Float(), nullable=True),
    sa.Column('hourly_cap', sa.Integer(), nullable=True),
    sa.Column('daily_cap', sa.Integer(), nullable=True),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('random_delay_min', sa.Integer(), nullable=True),
    sa.Column('random_delay_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_policies_account_id'), 'rate_policies', ['account_id'], unique=False)
    op.create_foreign_key(
        'fk_accounts_policy_id_rate_policies',
        'accounts',
        'rate_policies',
        ['policy_id'],
        ['id'],
    )
    op.create_table('channel_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('API_TOKEN', 'MTPROTO_SESSION', 'BROWSER_PROFILE', 'STRING_SESSION', name='sessiontype'), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_sessions_account_id'), 'channel_sessions', ['account_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('rendered_text', sa.Text(), nullable=True),
    sa.Column('media_ref', sa.String(length=1024), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('product_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['product_snapshot_id'], ['product_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_account_id'), 'messages', ['account_id'], unique=False)
    op.create_index(op.f('ix_messages_campaign_id'), 'messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_messages_contact_id'), 'messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_messages_dedupe_key'), 'messages', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_messages_product_snapshot_id'), 'messages', ['product_snapshot_id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('render_status', sa.Enum('PENDING', 'RENDERED', 'FAILED', name='renderstatus'), nullable=False),
    sa.Column('send_status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'ACCEPTED_BY_WORKER', 'ACCEPTED_BY_PLATFORM', 'DELIVERED', 'READ', 'FAILED_RETRYABLE', 'FAILED_PERMANENT', name='sendstatus'), nullable=False),
    sa.Column('final_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['final_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_campaign_recipient_campaign_contact')
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_recipients_campaign_send_status', 'campaign_recipients', ['campaign_id', 'send_status'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_contact_id'), 'campaign_recipients', ['contact_id'], unique=False)
    op.create_table('message_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'SUCCESS', 'FAILED_RETRYABLE', 'FAILED_PERMANENT', name='messageattemptstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('platform_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_attempts_message_id'), 'message_attempts', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_attempts_message_id'), table_name='message_attempts')
    op.drop_table('message_attempts')
    op.drop_index(op.f('ix_campaign_recipients_contact_id'), table_name='campaign_recipients')
    op.drop_index('ix_campaign_recipients_campaign_send_status', table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_messages_product_snapshot_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_dedupe_key'), table_name='messages')
    op.drop_index(op.f('ix_messages_contact_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_campaign_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_account_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_channel_sessions_account_id'), table_name='channel_sessions')
    op.drop_table('channel_sessions')
    op.drop_constraint('fk_accounts_policy_id_rate_policies', 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_rate_policies_account_id'), table_name='rate_policies')
    op.drop_table('rate_policies')
    op.drop_index(op.f('ix_product_snapshots_payload_hash'), table_name='product_snapshots')
    op.drop_table('product_snapshots')
    op.drop_index(op.f('ix_kb_documents_chunk_id'), table_name='kb_documents')
    op.drop_table('kb_documents')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_contacts_phone_e164'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_accounts_platform_status', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
